monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info
            channels: ["!event", "!php"]
            formatter: monolog.formatter.wo_brackets
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
